FROM nginx:1.21

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY cert/servicebus.local.crt /etc/nginx/certs/
COPY cert/servicebus.local.key /etc/nginx/certs/