FROM mcr.microsoft.com/dotnet/sdk:3.1 as backend

COPY /BackendForReadAudit /BackendForReadAudit

WORKDIR /BackendForReadAudit

RUN \
 dotnet restore BackendForReadAudit.sln;\
 dotnet build BackendForReadAudit.sln -c Debug;\
 dotnet publish BackendForReadAudit/BackendForReadAudit.csproj -c Debug -o out -f netcoreapp3.1

FROM mcr.microsoft.com/dotnet/aspnet:3.1

WORKDIR /app

COPY --from=backend /BackendForReadAudit/out ./

ENTRYPOINT ["dotnet", "BackendForReadAudit.dll"]